# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:12.18.0
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # Fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build

  deploy:
    docker:
      - image: circleci/node:12.18.0
    steps:
      - run: curl -X POST -d {} ${NETLIFY_DEPLOY_HOOK}

workflows:
  version: 2

  # Workflow for non-master or staging branches
  build:
    jobs:
      - build
    when:
      or:
        - equal: [ master, << pipeline.git.branch >> ]
        - equal: [ staging, << pipeline.git.branch >> ]

  # Workflow for staging branch
  build-and-deploy-staging:
    env:
      NETLIFY_DEPLOY_HOOK: ${NETLIFY_STAGING_DEPLOY_HOOK}
    jobs:
      - build
      - deploy:
          requires:
            - build
    when:
      equal: [ staging, << pipeline.git.branch >> ]
