version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.18.0
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # Fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build

  deploy-staging:
    docker:
      - image: circleci/node:12.18.0
    steps:
      - run: curl -X POST -d {} ${NETLIFY_STAGING_DEPLOY_HOOK}

  deploy-production:
    docker:
      - image: circleci/node:12.18.0
    steps:
      - run: curl -X POST -d {} ${NETLIFY_PRODUCTION_DEPLOY_HOOK}


workflows:
  # Workflow for non-master or staging branches
  build:
    jobs:
      - build
    when:
      or:
        - not:
            equal: [ master, << pipeline.git.branch >> ]
        - not:
            equal: [ staging, << pipeline.git.branch >> ]

  # Workflow for staging branch
  build-and-deploy-staging:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
    when:
      equal: [ staging, << pipeline.git.branch >> ]
