// React modules
import React, { useState, useEffect, createRef } from 'react'
import { ProjectCard } from '@components'
import { useStaticQuery, graphql } from 'gatsby'

// Styling modules
import styled, { css } from 'styled-components'
import { theme, Section } from '@theme'

// Misc. modules
import content from '@content/projects.yml'
import { generateKey } from '@utils'

// =============================================================================

/**
 * For this to work, each project in `projects.yml` must have a `imgSrc`
 * property set to the corresponding image file name.
 *
 * @example
 * imgSrc: project-mockup-small.png
 */
const Projects = () => {
    /**
     * Possible values:
     * - srcWebp
     * - src
     */
    const endAttr = 'srcWebp'

    const data = useStaticQuery(
        graphql`
            query loadProjectMockups {
                allImageSharp {
                    edges {
                        node {
                            fluid(maxWidth: 696, quality: 100) {
                                originalName
                                srcWebp
                            }
                        }
                    }
                }
            }
        `
    )

    /**
     * Creates a hash map where each key is the image file name and the value
     * is an object containing the `src` and `originalName` properties of
     * the image.
     */
    const imageHashMap = data.allImageSharp.edges.reduce((hashMap, edge) => {
        const imageDetails = edge.node.fluid
        if (hashMap[imageDetails.originalName]) {
            // Do something with duplicate entries
        } else {
            hashMap[imageDetails.originalName] = { ...imageDetails }
        }
        return hashMap
    }, {})

    /**
     * Updates the `imgSrc` property of each project object literal to the
     * `src` value generated by Gatsby.
     */
    const projects = content.projects.map((project) => ({
        ...project,
        imgSrc: imageHashMap[project.imgSrc]
            ? imageHashMap[project.imgSrc][endAttr]
            : imageHashMap['project-mockup-sample.png'][endAttr],
    }))

    /**
     * This portion handles the opacity of each project card. It uses an
     * intersection observer, observing each card.
     */

    const observer = new IntersectionObserver(
        (entries) => {
            entries.forEach((entry) => {
                if (entry.isIntersecting) {
                    entry.target.classList.add('opaque')
                } else {
                    entry.target.classList.remove('opaque')
                }
            })
        },
        { threshold: [0.7, 0.5, 0.5, 0.5] }
    )

    const observeElement = (ref) => observer.observe(ref)

    return (
        <Section id="projects" additionalStyles={additionalSectionStyles}>
            <Heading>{content.heading}</Heading>
            <ProjectList>
                {projects.map((project, i) => {
                    return (
                        <ProjectCard
                            key={generateKey(project.name, i)}
                            observeElement={observeElement}
                            {...project}
                        />
                    )
                })}
            </ProjectList>
        </Section>
    )
}

// =============================================================================

const colors = theme.colors
const heights = theme.dimensions.heights

const fontSizes = {
    heading: {
        xs: '28px',
        sm: '32px',
        md: '42px',
        lg: '50px',
        xl: '54px',
    },
}

// =============================================================================

const additionalSectionStyles = css`
    margin-top: 100px;

    /* The top offset is calculated by adding the navigation bar's height and
       the additional space. */
    padding-top: calc(${heights.navbar.md} + 48px);

    @media only screen and (min-width: 768px) {
        margin-top: 300px;
    }

    @media only screen and (min-width: 1024px) {
        margin-top: 300px;
    }

    @media only screen and (min-width: 1440px) {
        margin-top: 300px;
    }
`

// =============================================================================

const Heading = styled('h2')`
    position: relative;
    font-weight: 500;
    font-size: ${fontSizes.heading.xs};

    &::after {
        position: absolute;
        bottom: -18px;
        left: 0;
        width: 30%;
        height: 4px;
        background: rgba(${colors.blue}, 0.6);
        content: '';
    }

    @media only screen and (min-width: 568px) {
        font-size: ${fontSizes.heading.sm};
    }

    @media only screen and (min-width: 768px) {
        font-size: ${fontSizes.heading.md};
    }

    @media only screen and (min-width: 1024px) {
        font-size: ${fontSizes.heading.lg};

        &::after {
            height: 5px;
        }
    }

    @media only screen and (min-width: 1440px) {
        display: flex;
        justify-content: center;
        font-size: ${fontSizes.heading.xl};

        &::after {
            left: unset;
            height: 6px;
        }
    }
`

// =============================================================================

const ProjectList = styled('ul')`
    margin-top: 60px;

    @media only screen and (min-width: 768px) {
        margin-top: 90px;
    }

    @media only screen and (min-width: 1024px) {
        margin-top: 100px;
    }

    @media only screen and (min-width: 1440px) {
        margin-top: 130px;
    }
`

// =============================================================================

export default Projects
