// React modules
import React from 'react'
import { ProjectCard } from '@components'
import { useStaticQuery, graphql } from 'gatsby'

// Styling modules
import styled, { css } from 'styled-components'
import { theme, Section } from '@theme'

// Misc. modules
import content from '@content/projects.yml'
import { generateKey } from '@utils'

// =============================================================================

/**
 * For this to work, each project in `projects.yml` must have a `imgSrc`
 * property set to the corresponding image file name.
 *
 * @example
 * imgSrc: project-mockup-small.png
 */
const Projects = () => {
    const data = useStaticQuery(
        graphql`
            query loadProjectMockups {
                allImageSharp {
                    edges {
                        node {
                            fixed(pngQuality: 10) {
                                srcWebp
                                originalName
                            }
                        }
                    }
                }
            }
        `
    )

    /**
     * Creates a hash map where each key is the image file name and the value
     * is an object containing the `srcWebp` and `originalName` properties of
     * the image.
     */
    const imageHashMap = data.allImageSharp.edges.reduce((hashMap, edge) => {
        const imageDetails = edge.node.fixed
        if (hashMap[imageDetails.originalName]) {
            // Do something with duplicate entries
        } else {
            hashMap[imageDetails.originalName] = { ...imageDetails }
        }
        return hashMap
    }, {})

    /**
     * Updates the `imgSrc` property of each project object literal to the
     * `srcWebp` value generated by Gatsby.
     */
    const projects = content.projects.map((project) => ({
        ...project,
        imgSrc: imageHashMap[project.imgSrc]
            ? imageHashMap[project.imgSrc].srcWebp
            : imageHashMap['project-mockup-small.png'].srcWebp,
    }))

    return (
        <Section id="projects" additionalStyles={additionalSectionStyles}>
            <Heading>{content.heading}</Heading>
            <ProjectList>
                {projects.map((project, i) => {
                    return (
                        <ProjectCard
                            key={generateKey(project.name, i)}
                            {...project}
                        />
                    )
                })}
            </ProjectList>
        </Section>
    )
}

// =============================================================================

const colors = theme.colors
const heights = theme.dimensions.heights

const fontSizes = {
    heading: {
        xs: '28px',
        sm: '32px',
        md: '38px',
        lg: '48px',
        xl: '50px',
    },
}

// =============================================================================

const additionalSectionStyles = css`
    margin-top: 100px;

    /* The top offset is calculated by adding the navigation bar's height and
       the additional space. */
    padding-top: calc(${heights.navbar.md} + 48px);

    @media only screen and (min-width: 768px) {
        margin-top: 300px;
    }

    @media only screen and (min-width: 1024px) {
        margin-top: 300px;
    }

    @media only screen and (min-width: 1440px) {
        margin-top: 300px;
    }
`

// =============================================================================

const Heading = styled('h2')`
    position: relative;
    font-weight: 500;
    font-size: ${fontSizes.heading.xs};

    &::after {
        position: absolute;
        bottom: -18px;
        left: 0;
        width: 30%;
        height: 4px;
        background: rgba(${colors.blue}, 0.6);
        content: '';
    }

    @media only screen and (min-width: 568px) {
        font-size: ${fontSizes.heading.sm};
    }

    @media only screen and (min-width: 768px) {
        font-size: ${fontSizes.heading.md};
    }

    @media only screen and (min-width: 1024px) {
        font-size: ${fontSizes.heading.lg};
    }

    @media only screen and (min-width: 1440px) {
        font-size: ${fontSizes.heading.xl};
    }
`

// =============================================================================

const ProjectList = styled('ul')`
    margin-top: 60px;

    @media only screen and (min-width: 768px) {
        margin-top: 70px;
    }

    @media only screen and (min-width: 1024px) {
        margin-top: 120px;
    }

    @media only screen and (min-width: 1440px) {
        margin-top: 150px;
    }
`

// =============================================================================

export default Projects
