export { default as Head } from './Head'
export { default as Navbar } from './Navbar'
export { default as Background } from './Background'
export { default as ProjectCard } from './ProjectCard'
// export { default as Footer } from './Footer'
